course_page: "https://mfaratoon-nebvh2nc.manus.space/course"
wa_ai_chatbot: "https://chat.whatsapp.com/KzkcjwraeYhCsUXaexgNyM"
wa_ai_video: "https://chat.whatsapp.com/G9phNqLyJ3L2RV4lprLUb7"
wa_ai_automation: "https://chat.whatsapp.com/BRk1xgsg4ohKAaWN7oDRIe"
telegram_updates: "https://t.me/+eJxxMKtunMcwODhk"
telegram_tools: "https://t.me/Farsamada"
youtube: "https://m.youtube.com/user/MrFaraton"
facebook: "https://www.facebook.com/soomaalipodcast"
substack: "https://mfaratoon.substack.com/"
google_classroom: "https://classroom.google.com/c/ODAzMzUwNDIyOTU0?cjc=sdvvlyc2"
